export const enumProducts = [
  {
    name: 'Smartphone X1',
    count: 50,
    price: 699,
    desc: 'Latest smartphone with AMOLED display and fast processor.',
    category: 'Electronics',
    brand: 'TechBrand',
  },
  {
    name: 'Wireless Headphones Pro',
    count: 120,
    price: 199,
    desc: 'Noise-cancelling over-ear headphones with long battery life.',
    category: 'Audio',
    brand: 'SoundWave',
  },
  {
    name: 'Gaming Laptop G5',
    count: 30,
    price: 1499,
    desc: 'High-performance laptop with RTX graphics card and 16GB RAM.',
    category: 'Computers',
    brand: 'GameTech',
  },
  {
    name: '4K LED TV 55"',
    count: 20,
    price: 799,
    desc: 'Ultra HD television with smart features and HDR support.',
    category: 'Electronics',
    brand: 'VisionPlus',
  },
  {
    name: 'Electric Kettle 1.7L',
    count: 75,
    price: 49,
    desc: 'Fast-boiling kettle with auto shut-off and boil-dry protection.',
    category: 'Home Appliances',
    brand: 'KitchenMaster',
  },
  {
    name: 'Running Shoes AirFlex',
    count: 200,
    price: 120,
    desc: 'Lightweight and comfortable running shoes with breathable mesh.',
    category: 'Sportswear',
    brand: 'SpeedRun',
  },
  {
    name: 'Smartwatch Series 7',
    count: 90,
    price: 299,
    desc: 'Fitness tracker and smartwatch with heart rate monitor.',
    category: 'Wearables',
    brand: 'TimeTech',
  },
  {
    name: 'Coffee Maker Deluxe',
    count: 40,
    price: 249,
    desc: 'Automatic drip coffee maker with programmable timer and grinder.',
    category: 'Kitchen Appliances',
    brand: 'BrewMaster',
  },
  {
    name: 'Smartphone X2 Ultra',
    count: 45,
    price: 829,
    desc: 'Next-gen smartphone with curved AMOLED display and triple-lens camera.',
    category: 'Electronics',
    brand: 'TechBrand',
  },
  {
    name: 'Wireless Earbuds Max',
    count: 140,
    price: 179,
    desc: 'True wireless earbuds with ANC and wireless charging case.',
    category: 'Audio',
    brand: 'SoundWave',
  },
  {
    name: 'Gaming Laptop G7 Pro',
    count: 28,
    price: 1699,
    desc: 'Powerful gaming laptop with RTX 4070 GPU and 32GB DDR5 RAM.',
    category: 'Computers',
    brand: 'GameTech',
  },
  {
    name: '4K QLED TV 65"',
    count: 18,
    price: 999,
    desc: 'Smart QLED TV with HDR10+ and built-in voice control.',
    category: 'Electronics',
    brand: 'VisionPlus',
  },
  {
    name: 'Electric Kettle RapidBoil',
    count: 70,
    price: 59,
    desc: 'Quick-boiling kettle with LED indicator and stainless steel design.',
    category: 'Home Appliances',
    brand: 'KitchenMaster',
  },
  {
    name: 'Running Shoes AeroFlex',
    count: 210,
    price: 110,
    desc: 'Breathable running shoes with flexible sole and cushioned heel.',
    category: 'Sportswear',
    brand: 'SpeedRun',
  },
  {
    name: 'Smartwatch Series 8',
    count: 85,
    price: 329,
    desc: 'Advanced smartwatch with GPS, ECG, and fitness tracking features.',
    category: 'Wearables',
    brand: 'TimeTech',
  },
  {
    name: 'Coffee Maker Premium Plus',
    count: 35,
    price: 279,
    desc: 'High-end coffee maker with touch display and built-in milk frother.',
    category: 'Kitchen Appliances',
    brand: 'BrewMaster',
  },
  {
    name: 'Noise-Cancelling Headphones Ultra',
    count: 60,
    price: 249,
    desc: 'Over-ear headphones with premium sound quality and long battery life.',
    category: 'Audio',
    brand: 'SoundWave',
  },
  {
    name: 'Smart Home Hub 3.0',
    count: 25,
    price: 399,
    desc: 'Centralized smart home controller with voice assistant support.',
    category: 'Electronics',
    brand: 'TechBrand',
  },
  {
    name: 'Noise-Cancelling Headphones Ultra',
    count: 60,
    price: 249,
    desc: 'Over-ear headphones with premium sound quality and long battery life.',
    category: 'Audio',
    brand: 'SoundWave',
  },
  {
    name: 'Smart Home Hub 3.0',
    count: 25,
    price: 399,
    desc: 'Centralized smart home controller with voice assistant support.',
    category: 'Electronics',
    brand: 'TechBrand',
  },
];
